version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    container_name: espressionist_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: espressionist_ecommerce
      MYSQL_USER: espressionist_user
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
