package com.espressionist_ecommerce.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;
import lombok.Data;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
public class ProductDTO {
    private Long id; // Not validated on input for creation, generated by DB

    @NotBlank(message = "Product name is required")
    private String name;

    @NotNull(message = "Price is required")
    @PositiveOrZero(message = "Price must be zero or positive")
    private BigDecimal price;

    @NotBlank(message = "Category is required")
    private String category;

    private String image; // Optional, can be set via separate upload

    @NotNull(message = "Stock is required")
    @PositiveOrZero(message = "Stock must be zero or positive")
    private Integer stock;

    @NotBlank(message = "Description is required")
    private String description;

    private Boolean archived; // Typically set by service logic, not direct input for true/false
    private LocalDateTime createdAt; // Output only
    private LocalDateTime updatedAt; // Output only
}
