package com.espressionist_ecommerce.dto;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;
import lombok.Data;

/**
 * Purpose: DTO for product data transfer, including validation for required fields.
 * This class is used to encapsulate the data required for product operations,
 * ensuring that all necessary fields are provided and validated before processing.
 */
@Data
/**
 * This class is used to transfer product data between layers of the application,
 * ensuring that the necessary information is available for product creation and updates.
 */
public class ProductDTO {
    private Long id; // Not validated on input for creation, generated by DB
    /**
     * Name of the product.
     * Must not be blank.
     */
    @NotBlank(message = "Product name is required")
    private String name;
    /**
     * Price of the product.
     * Must be provided and must be zero or positive.
     *
     * Note: This DTO uses Double for price to simplify JSON mapping with the frontend.
     * The entity uses BigDecimal for precision. All conversions between DTO and entity
     * should use BigDecimal.valueOf(price) and .doubleValue() for consistency.
     */
    @NotNull(message = "Price is required")
    @PositiveOrZero(message = "Price must be zero or positive")
    private Double price; // Accept as Double for easier JSON mapping from frontend
    /**
     * Category of the product.
     * Must not be blank.
     */
    @NotBlank(message = "Category is required")
    private String category;
    private String image; // Optional, can be set via separate upload
    /**
     * Stock quantity of the product.
     * Must be provided and must be zero or positive.
     */
    @NotNull(message = "Stock is required")
    @PositiveOrZero(message = "Stock must be zero or positive")
    private Integer stock;
    /**
     * Description of the product.
     * Must not be blank.
     */
    @NotBlank(message = "Description is required")
    private String description;
    private Boolean archived; 
}
