version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: espressionist_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: espressionist_ecommerce
      MYSQL_USER: espressionist_user
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: